<a href="https://colab.research.google.com/github/hirajya/CCMACLRL_EXERCISES_COM222/blob/main/Exercise_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset Logistic Regression

## Importing Modules

In [632]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Fetching Dataset

In [633]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/f5fdfba1aabbbafcf2fe49ca6e1c8f92f69d1458/datasets/titanic/train.csv?raw=true'
test_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/f5fdfba1aabbbafcf2fe49ca6e1c8f92f69d1458/datasets/titanic/test.csv?raw=true'

df = pd.read_csv(dataset_url)
dt=pd.read_csv(test_url)

In [634]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [635]:
dt.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## Dataset Analysis

In [636]:
df.shape

(891, 12)

In [637]:
dt.shape

(418, 11)

In [638]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [639]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [640]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [641]:
dt.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

## Data Preprocessing

In [642]:


# Define a function to remove outliers using the IQR method and report counts
def remove_outliers_iqr(df, column):
    # Count rows before removing outliers
    before_count = df.shape[0]

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Filter the DataFrame to remove outliers
    df_filtered = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

    # Count rows after removing outliers
    after_count = df_filtered.shape[0]

    # Print the counts
    print(f"Removing outliers from '{column}':")
    print(f"Before: {before_count}, After: {after_count}\n")

    return df_filtered

# Remove outliers for the 'Age' and 'Fare' columns
df = remove_outliers_iqr(df, 'Age')
df = remove_outliers_iqr(df, 'Fare')

Removing outliers from 'Age':
Before: 891, After: 703

Removing outliers from 'Fare':
Before: 703, After: 607

In [643]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin', 'Embarked'],inplace=True)
dt.drop(columns=['PassengerId','Name','Ticket','Cabin', 'Embarked'], inplace=True)

In [644]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Convert 'Sex' to numerical values
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
dt['Sex'] = dt['Sex'].map({'male': 0, 'female': 1})

df['Fare'].fillna(df['Fare'].median(), inplace=True)
dt['Fare'].fillna(dt['Fare'].median(), inplace=True)


# Handle missing values in 'Age' (you can choose a different strategy if needed)
df['Age'].fillna(df['Age'].median(), inplace=True)
dt['Age'].fillna(dt['Age'].median(), inplace=True)

In [645]:
def convert_age(df, cut_off_values, label_names):
    df["Age"] = df["Age"].fillna(-0.5)
    df["Age_Categories"] = pd.cut(df["Age"], cut_off_values, label_names)
    return df

cut_off_values = [-1, 0, 5, 12, 18, 35, 60, 100]
label_names = ["Missing", "Infant", "Child", "Teenager", "Young Adult", "Adult", "Senior"]

df = convert_age(df, cut_off_values, label_names)
dt = convert_age(dt, cut_off_values, label_names)

# age_plot = df.pivot_table(index = "Age_Categories", values = "Survived")
# age_plot.plot.bar()
# plt.show()

In [646]:
def create_dummies(df, column_name):
    dummies = pd.get_dummies(df[column_name], prefix = column_name)
    df = pd.concat([df, dummies], axis = 1)
    return df

df = create_dummies(df, "Pclass")
dt = create_dummies(dt, "Pclass")

df = create_dummies(df, "Age_Categories")
dt = create_dummies(dt, "Age_Categories")

df = create_dummies(df, "Sex")
dt = create_dummies(dt, "Sex")

df.head(10)
dt.head(10)

,Pclass,Sex,Age,SibSp,Parch,Fare,Age_Categories,Pclass_1,Pclass_2,Pclass_3,"Age_Categories_(-1, 0]","Age_Categories_(0, 5]","Age_Categories_(5, 12]","Age_Categories_(12, 18]","Age_Categories_(18, 35]","Age_Categories_(35, 60]","Age_Categories_(60, 100]",Sex_0,Sex_1
0,3,0,34.5,0,0,7.8292,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
1,3,1,47.0,1,0,7.0000,"(35, 60]",False,False,True,False,False,False,False,False,True,False,False,True
2,2,0,62.0,0,0,9.6875,"(60, 100]",False,True,False,False,False,False,False,False,False,True,True,False
3,3,0,27.0,0,0,8.6625,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
4,3,1,22.0,1,1,12.2875,"(18, 35]",False,False,True,False,False,False,False,True,False,False,False,True
5,3,0,14.0,0,0,9.2250,"(12, 18]",False,False,True,False,False,False,True,False,False,False,True,False
6,3,1,30.0,0,0,7.6292,"(18, 35]",False,False,True,False,False,False,False,True,False,False,False,True
7,2,0,26.0,1,1,29.0000,"(18, 35]",False,True,False,False,False,False,False,True,False,False,True,False
8,3,1,18.0,0,0,7.2292,"(12, 18]",False,False,True,False,False,False,True,False,False,False,False,True
9,3,0,21.0,2,0,24.1500,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False

In [647]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Age_Categories,Pclass_1,Pclass_2,Pclass_3,"Age_Categories_(-1, 0]","Age_Categories_(0, 5]","Age_Categories_(5, 12]","Age_Categories_(12, 18]","Age_Categories_(18, 35]","Age_Categories_(35, 60]","Age_Categories_(60, 100]",Sex_0,Sex_1
0,0,3,0,22.0,1,0,7.2500,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
2,1,3,1,26.0,0,0,7.9250,"(18, 35]",False,False,True,False,False,False,False,True,False,False,False,True
3,1,1,1,35.0,1,0,53.1000,"(18, 35]",True,False,False,False,False,False,False,True,False,False,False,True
4,0,3,0,35.0,0,0,8.0500,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
6,0,1,0,54.0,0,0,51.8625,"(35, 60]",True,False,False,False,False,False,False,False,True,False,True,False

## Training Model

In [648]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Age_Categories,Pclass_1,Pclass_2,Pclass_3,"Age_Categories_(-1, 0]","Age_Categories_(0, 5]","Age_Categories_(5, 12]","Age_Categories_(12, 18]","Age_Categories_(18, 35]","Age_Categories_(35, 60]","Age_Categories_(60, 100]",Sex_0,Sex_1
0,0,3,0,22.0,1,0,7.2500,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
2,1,3,1,26.0,0,0,7.9250,"(18, 35]",False,False,True,False,False,False,False,True,False,False,False,True
3,1,1,1,35.0,1,0,53.1000,"(18, 35]",True,False,False,False,False,False,False,True,False,False,False,True
4,0,3,0,35.0,0,0,8.0500,"(18, 35]",False,False,True,False,False,False,False,True,False,False,True,False
6,0,1,0,54.0,0,0,51.8625,"(35, 60]",True,False,False,False,False,False,False,False,True,False,True,False

In [649]:
# # Define features (X) and target (y)
# X = df.drop(columns=['Survived'])
# y = df['Survived']

# # Create and train the Logistic Regression model
# model = LogisticRegression()
# model.fit(X, y)

# dt_train= dt[['Sex', 'Age', 'SibSp', 'Parch', 'Fare']]


# # Make predictions on the test set
# # y_pred = model.predict(dt_train)

# # # Evaluate the model
# # accuracy = accuracy_score(y_test, y_pred)
# # print(f"Accuracy: {accuracy}")

In [650]:
# import pandas as pd
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score

# # Example to convert Age_Categories to midpoints if it's an Interval type
# df['Age_Categories'] = df['Age_Categories'].apply(lambda x: x.mid)

# # Define features (X) and target (y)
# X = df.drop(columns=['Survived'])
# y = df['Survived']

# # Ensure all columns are of appropriate types for Logistic Regression
# X = X.select_dtypes(include=['int64', 'float64', 'bool']).copy()  # Only keep numerical columns

# # Create and train the Logistic Regression model
# model = LogisticRegression()
# model.fit(X, y)

# # Prepare your test set (ensure it matches the format of X)
# dt_train = df.drop(columns=['Survived'])
# # Make sure dt_train has the same columns as X after processing

# # Make predictions on the test set
# # y_pred = model.predict(dt_train)

# # Evaluate the model (you may need to define y_test)
# # accuracy = accuracy_score(y_test, y_pred)
# # print(f"Accuracy: {accuracy}")

In [651]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Age_Categories', 'Pclass_1', 'Pclass_2', 'Pclass_3',
       'Age_Categories_(-1, 0]', 'Age_Categories_(0, 5]',
       'Age_Categories_(5, 12]', 'Age_Categories_(12, 18]',
       'Age_Categories_(18, 35]', 'Age_Categories_(35, 60]',
       'Age_Categories_(60, 100]', 'Sex_0', 'Sex_1'],
      dtype='object')

In [652]:
from sklearn.linear_model import LogisticRegression

column_names = ['Pclass_1', 'Pclass_2', 'Pclass_3', 'Sex_0', 'Sex_1',
       'Age_Categories_(-1, 0]', 'Age_Categories_(0, 5]',
       'Age_Categories_(5, 12]','Age_Categories_(12, 18]',
       'Age_Categories_(18, 35]','Age_Categories_(35, 60]', 'Age_Categories_(60, 100]']

lr = LogisticRegression()

lr.fit(df[column_names], df['Survived'])

LogisticRegression()

In [653]:
sample_submission_url ='https://github.com/robitussin/CCMACLRL_EXERCISES/blob/f5fdfba1aabbbafcf2fe49ca6e1c8f92f69d1458/datasets/titanic/gender_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

In [654]:
df.drop(columns=['Survived'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 607 entries, 0 to 890
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pclass                    607 non-null    int64
 1   Sex                       607 non-null    int64
 2   Age                       607 non-null    float64
 3   SibSp                     607 non-null    int64
 4   Parch                     607 non-null    int64
 5   Fare                      607 non-null    float64
 6   Age_Categories            607 non-null    category
 7   Pclass_1                  607 non-null    bool
 8   Pclass_2                  607 non-null    bool
 9   Pclass_3                  607 non-null    bool
 10  Age_Categories_(-1, 0]    607 non-null    bool
 11  Age_Categories_(0, 5]     607 non-null    bool
 12  Age_Categories_(5, 12]    607 non-null    bool
 13  Age_Categories_(12, 18]   607 non-null    bool
 14  Age_Categories_(18, 35]   607 non-null    bool
 15  Age_Categories_(35, 60]   607 non-null    bool
 16  Age_Categories_(60, 100]  607 non-null    bool
 17  Sex_0                     607 non-null    bool
 18  Sex_1                     607 non-null    bool
dtypes: bool(12), category(1), float64(2), int64(4)
memory usage: 41.3 KB

In [655]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 607 entries, 0 to 890
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pclass                    607 non-null    int64
 1   Sex                       607 non-null    int64
 2   Age                       607 non-null    float64
 3   SibSp                     607 non-null    int64
 4   Parch                     607 non-null    int64
 5   Fare                      607 non-null    float64
 6   Age_Categories            607 non-null    category
 7   Pclass_1                  607 non-null    bool
 8   Pclass_2                  607 non-null    bool
 9   Pclass_3                  607 non-null    bool
 10  Age_Categories_(-1, 0]    607 non-null    bool
 11  Age_Categories_(0, 5]     607 non-null    bool
 12  Age_Categories_(5, 12]    607 non-null    bool
 13  Age_Categories_(12, 18]   607 non-null    bool
 14  Age_Categories_(18, 35]   607 non-null    bool
 15  Age_Categories_(35, 60]   607 non-null    bool
 16  Age_Categories_(60, 100]  607 non-null    bool
 17  Sex_0                     607 non-null    bool
 18  Sex_1                     607 non-null    bool
dtypes: bool(12), category(1), float64(2), int64(4)
memory usage: 41.3 KB

In [656]:
dt.isnull().sum()

Pclass                      0
Sex                         0
Age                         0
SibSp                       0
Parch                       0
Fare                        0
Age_Categories              0
Pclass_1                    0
Pclass_2                    0
Pclass_3                    0
Age_Categories_(-1, 0]      0
Age_Categories_(0, 5]       0
Age_Categories_(5, 12]      0
Age_Categories_(12, 18]     0
Age_Categories_(18, 35]     0
Age_Categories_(35, 60]     0
Age_Categories_(60, 100]    0
Sex_0                       0
Sex_1                       0
dtype: int64

In [657]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pclass                    418 non-null    int64
 1   Sex                       418 non-null    int64
 2   Age                       418 non-null    float64
 3   SibSp                     418 non-null    int64
 4   Parch                     418 non-null    int64
 5   Fare                      418 non-null    float64
 6   Age_Categories            418 non-null    category
 7   Pclass_1                  418 non-null    bool
 8   Pclass_2                  418 non-null    bool
 9   Pclass_3                  418 non-null    bool
 10  Age_Categories_(-1, 0]    418 non-null    bool
 11  Age_Categories_(0, 5]     418 non-null    bool
 12  Age_Categories_(5, 12]    418 non-null    bool
 13  Age_Categories_(12, 18]   418 non-null    bool
 14  Age_Categories_(18, 35]   418 non-null    bool
 15  Age_Categories_(35, 60]   418 non-null    bool
 16  Age_Categories_(60, 100]  418 non-null    bool
 17  Sex_0                     418 non-null    bool
 18  Sex_1                     418 non-null    bool
dtypes: bool(12), category(1), float64(2), int64(4)
memory usage: 25.4 KB

In [658]:
# id = sf.pop('PassengerId')
y_pred = lr.predict(dt[column_names])

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'PassengerID': id,
    'Survived': y_pred
})

# Save the submission DataFrame to a CSV file
file_name = 'submission_fileTtabsagad.csv'
submission_df.to_csv(file_name, index=False)
print(f"Submission file created: {file_name}")

Submission file created: submission_fileTtabsagad.csv